# Generated by Django 2.1 on 2018-11-30 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['created_at'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.AddField(
            model_name='teachers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
