# Generated by Django 2.1 on 2018-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.TextField(max_length=200, null=True)),
                ('phone_number', models.TextField(max_length=200, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
