# Generated by Django 2.1 on 2018-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20181201_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
